package com.github.rmheuer.azalea.input.keyboard;

public enum Key {
    UNKNOWN("Unknown"),
    SPACE("Space"),
    APOSTROPHE("Apostrophe"),
    COMMA("Comma"),
    MINUS("Minus"),
    PERIOD("Period"),
    SLASH("Slash"),
    ZERO("Zero"),
    ONE("One"),
    TWO("Two"),
    THREE("Three"),
    FOUR("Four"),
    FIVE("Five"),
    SIX("Six"),
    SEVEN("Seven"),
    EIGHT("Eight"),
    NINE("Nine"),
    SEMICOLON("Semicolon"),
    EQUALS("Equals"),
    A("A"),
    B("B"),
    C("C"),
    D("D"),
    E("E"),
    F("F"),
    G("G"),
    H("H"),
    I("I"),
    J("J"),
    K("K"),
    L("L"),
    M("M"),
    N("N"),
    O("O"),
    P("P"),
    Q("Q"),
    R("R"),
    S("S"),
    T("T"),
    U("U"),
    V("V"),
    W("W"),
    X("X"),
    Y("Y"),
    Z("Z"),
    LEFT_BRACKET("Left Bracket"),
    RIGHT_BRACKET("Right Bracket"),
    GRAVE_ACCENT("Grave Accent"),
    WORLD_1("World 1"),
    WORLD_2("World 2"),
    ESCAPE("Escape"),
    ENTER("Enter"),
    TAB("Tab"),
    BACKSPACE("Backspace"),
    INSERT("Insert"),
    DELETE("Delete"),
    RIGHT("Right Arrow"),
    LEFT("Left Arrow"),
    DOWN("Down Arrow"),
    UP("Up Arrow"),
    PAGE_UP("Page Up"),
    PAGE_DOWN("Page Down"),
    HOME("Home"),
    END("End"),
    CAPS_LOCK("Caps Lock"),
    SCROLL_LOCK("Scroll Lock"),
    NUM_LOCK("Num Lock"),
    PRINT_SCREEN("Print Screen"),
    PAUSE("Pause"),
    F1("F1"),
    F2("F2"),
    F3("F3"),
    F4("F4"),
    F5("F5"),
    F6("F6"),
    F7("F7"),
    F8("F8"),
    F9("F9"),
    F10("F10"),
    F11("F11"),
    F12("F12"),
    F13("F13"),
    F14("F14"),
    F15("F15"),
    F16("F16"),
    F17("F17"),
    F18("F18"),
    F19("F19"),
    F20("F20"),
    F21("F21"),
    F22("F22"),
    F23("F23"),
    F24("F24"),
    F25("F25"),
    NUMPAD_ZERO("Numpad Zero"),
    NUMPAD_ONE("Numpad One"),
    NUMPAD_TWO("Numpad Two"),
    NUMPAD_THREE("Numpad Three"),
    NUMPAD_FOUR("Numpad Four"),
    NUMPAD_FIVE("Numpad Five"),
    NUMPAD_SIX("Numpad Six"),
    NUMPAD_SEVEN("Numpad Seven"),
    NUMPAD_EIGHT("Numpad Eight"),
    NUMPAD_NINE("Numpad Nine"),
    NUMPAD_DECIMAL("Numpad Decimal Point"),
    NUMPAD_DIVIDE("Numpad Divide"),
    NUMPAD_MULTIPLY("Numpad Multiply"),
    NUMPAD_SUBTRACT("Numpad Subtract"),
    NUMPAD_ADD("Numpad Add"),
    NUMPAD_ENTER("Numpad Enter"),
    NUMPAD_EQUALS("Numpad Equals"),
    LEFT_SHIFT("Left Shift"),
    LEFT_CONTROL("Left Control"),
    LEFT_ALT("Left Alt"),
    LEFT_SUPER("Left Super"),
    RIGHT_SHIFT("Right Shift"),
    RIGHT_CONTROL("Right Control"),
    RIGHT_ALT("Right Alt"),
    RIGHT_SUPER("Right Super"),
    MENU("Menu");

    private final String name;

    Key(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
